application: medloot
version: 1
runtime: python27
api_version: 1
threadsafe: no
libraries:
- name: jinja2
  version: latest

inbound_services:
- mail

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /static
  static_dir: static

- url: /admin.*
  script: main.app
  login: required
  secure: always

- url: /_ah/mail/support@.*medloot\.appspotmail\.com
  script: mail.app
  login: admin

- url: .*
  script: main.app
  secure: always


